name: CI
on:
  push:
    branches: [main]
    paths:
      - 'ml/**'
      - 'model/**'
      - 'test_ml.py'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest flake8
      - name: Run tests
        run: pytest test_ml.py -v
      - name: Lint
        run: flake8 . --max-line-length=127 --count